HMS.UI/Controllers/PharmacyController.cs
using HMS.Entity.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace HMS.UI.Controllers
{
    public class PharmacyController : Controller
    {
        private IConfiguration _configuration;
        public PharmacyController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> PharmacyIndex()
        {
            IEnumerable<Pharmacy> pharmacyresult = null;
            using (HttpClient client = new HttpClient())
            {
                string endPoint = _configuration["WebApiBaseUrl"] + "Pharmacy/GetMedicines";
                using (var response = await client.GetAsync(endPoint))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        var result = await response.Content.ReadAsStringAsync();
                        pharmacyresult = JsonConvert.DeserializeObject<IEnumerable<Pharmacy>>(result);
                    }
                }
            }
            return View(pharmacyresult);
        }
        public IActionResult AddMedicine()
        {
            return View();
        }
        [HttpPost("AddMedicine")]
        public async Task<IActionResult> AddMedicine(Pharmacy pharmacy)
        {
            ViewBag.status = "";
            using (HttpClient client = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(pharmacy), Encoding.UTF8, "application/json");
                string endPoint = _configuration["WebApiBaseUrl"] + "Pharmacy/AddMedicine";
                using (var response = await client.PostAsync(endPoint, content))
                {
                    if (response.StatusCode == System.Net.HttpStatusCode.OK)
                    {
                        ViewBag.status = "Ok";
                        ViewBag.message = "  Medicine details saved successfully!";
                    }
                    else
                    {
                        ViewBag.status = "Error";
                        ViewBag.message = "Wrong entries!";
                    }
                }
            }
            return View();
        }
    }
    
}

HMS.UI/Views/Pharmacy/AddMedicine.cshtml
@model HMS.Entity.Models.Pharmacy

@{
    ViewData["Title"] = "AddMedicine";
}
<form method="post" enctype="multipart/form-data">
    <h1>Pharmacy Details</h1>
</form>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddMedicine">
            <div class="form-group">
                <label asp-for="MedicineName" class="control-label"></label>
                <input asp-for="MedicineName" class="form-control" />
                <span asp-validation-for="MedicineName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicineIssue" class="control-label"></label>
                <input asp-for="MedicineIssue" class="form-control" />
                <span asp-validation-for="MedicineIssue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MedicineTime" class="control-label"></label>
                <input asp-for="MedicineTime" class="form-control" />
                <span asp-validation-for="MedicineTime" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="pharmacyStock" class="control-label"></label>
                <input asp-for="pharmacyStock" class="form-control" />
                <span asp-validation-for="pharmacyStock" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
            @if (ViewBag.status == "Ok")
            {
                <div class="alert alert-success">
                    @ViewBag.message
                </div>
            }
            else if (ViewBag.status == "Error")
            {
                <div class="alert alert-danger">
                    @ViewBag.message
                </div>
            }
        </form>
    </div>
</div>
<div>
    <a asp-action="PharmacyIndex">Back to List</a>
</div>

HMS.UI/Views/Pharmacy/PharmacyIndex.cshtml
@model IEnumerable<HMS.Entity.Models.Pharmacy>

<div class="row">
    <div class="col-12">
        <h3>Pharmacy Details</h3>
        <hr />
        <table class="table table-light table-bordered table-hover">
            <thead>
                <tr>
                    <th>Medicine ID</th>
                    <th>Patient Id </th>
                    <th> Doctor Id</th>
                    <th>Medicine Name</th>
                    <th> Medicine Issue</th>
                    <th> Medicine Time</th>
                    <th> pharmacyStock</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>


                @foreach (var pharmacy in Model)
                {

                    <tr>
                        <td>@pharmacy.MedicineId</td>
                        <td>@pharmacy.PatientId</td>
                        <td>@pharmacy.DoctorId</td>
                        <td>@pharmacy.MedicineName</td>
                        <td>@pharmacy.MedicineIssue</td>
                        <td>@pharmacy.MedicineTime</td>
                        <td>@pharmacy.pharmacyStock</td>



                        <td><a asp-controller="Pharmacy" asp-action="UpdateMedicine" asp-route-MovieId="@pharmacy.MedicineId">Update</a></td>
                        <td><a asp-controller="Pharmacy" asp-action="DeleteMedicine" asp-route-MovieId="@pharmacy.MedicineId">Delete</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>